### ISSUE TITLE
kaiostech/kdeploy nolonger exists.

### ISSUE THREAD

**Issue by Losses** [kaiostech/sample-react#4]
Not only disappeared on GitHub, but also disappeared on npm.

**Comment by seinlin** [comment]
Resolved.

**Comment by landsman** [comment]
@seinlin how? still not found

**Comment by seinlin** [comment]
@landsman In Readme, there are two pages about setup and install the app to the device. Does it help?
https://github.com/kaiostech/sample-react#send-the-app-to-a-kaios-device

**Comment by BobFactory** [comment]
Hi @seinlin . I started out with KaiOS today. Unfortunately yarn install is failing after cloning because of this issue.  

"https://codeload.github.com/kaiostech/kdeploy/tar.gz/e6c18477f66742e29afe2bf42e9e0691e4a59afb: Request failed \"404 Not Found\"".

Can you please suggest what could have gone wrong ?

**Comment by PaulKish** [comment]
This is still broken getting a 404 for kdeploy

**Comment by lisleguo** [comment]
Is this issue solved? I met this issue when I tried it today, I encountered this issue.
